VERSION = "0.6.0"
SOYA_DID_DRI = "z3wmSSwhcQN4bgJHtgYqSLmdqRvv8Tnv189krACn1GtJE"
SOYA_REPO = "https://soya.ownyourdata.eu"
SOYA_WEB_CLI = "https://soya-web-cli.ownyourdata.eu"
UNIRESOLVER_URL = "https://dev.uniresolver.io"