apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: didlint-tls
  annotations:
    cert-manager.io/issuer: "letsencrypt-prod"
spec:
  secretName: didlint-tls
  issuerRef:
    group: cert-manager.io
    name: letsencrypt-prod
    kind: Issuer
  dnsNames:
  - 'didlint.ownyourdata.eu'