apiVersion: apps/v1
kind: Deployment
metadata:
  name: didlint
spec:
  replicas: 2
  selector:
    matchLabels:
      app: didlint
  template:
    metadata:
      labels:
        app: didlint
    spec:
      containers:
      - name: didlint
        image: oydeu/didlint:latest
        ports:
        - containerPort: 3000
        env:
          - name: LANG
            value: C.UTF-8
          - name: RAILS_LOG_TO_STDOUT
            value: "TRUE"
          - name: RAILS_SERVE_STATIC_FILES
            value: "TRUE"
          - name: RAILS_ENV
            value: production
          - name: SOYA_DID_DRI
            value: zQmc76XfAkKxjFhHUANsq2yLxvt1FNkwHULChENskd9PJ9T
          - name: allowed_hosts
            value: "didlint.ownyourdata.eu"
          - name: SECRET_KEY_BASE
            value: "secret"
